version: '3.5'

networks:
  backend:
    driver: 'bridge'

services:
  php-fpm:
    build:
      context: php-fpm
    working_dir: /var/www
    volumes:
      - ../:/var/www
    networks:
      - backend

  nginx:
    build:
      context: nginx
    working_dir: /var/www
    volumes:
      - ../:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - php-fpm
